import Head from "next/head";
import styles from "../styles/custom404.module.scss";
import Link from "next/link";

const Custom404 = () => {
  return (
    <>
      <Head>
        <title>MicheleVacca.it</title>
        <meta name="description" content="Generated by Michele" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ico/Michele.ico" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="Come Fare - Michele Vacca" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.il-blog-di-michele-vacca.it" />
        <meta property="og:image" content="/ico/Michele.ico" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Come Fare - Michele Vacca" />
        <meta name="twitter:image" content="/ico/Michele.ico" />
        <script type="application/ld+json">
            {`
            {
              "@context": "https://schema.org",
              "@type": "Organization",
              "url": "https://www.il-blog-di-michele-vacca.it",
              "logo": "/ico/Michele.ico",
              "name": "Michele Vacca",
              "sameAs": [
                "https://www.tiktok.com/@michele.vacca.blog?_t=8mrJ15DgGkS&_r=1",
                "https://www.instagram.com/blogdimichelevacca/?igsh=MXBiMHh4NnB2NGtubQ%3D%3D",
                "https://www.facebook.com/profile.php?id=100063728582740"
              ]
            }
          `}
        </script>
      </Head>
      <div className={styles.Custom404}>
        <h1>Errore 404</h1>
        <p>la pagina che stai cercando di visualizare non esiste.</p>
        <Link className={styles.home404} href="/">
          torna alla home
        </Link>
      </div>
    </>
  );
};

export default Custom404;