import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MicheleVacca.it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Politica e attualità dal punto di vista di un libero studente" />
        <link rel="icon" href="/ico/Michele.ico" />
      </Head>
      <main className={styles.main}>
       <Layout/>
      </main>
    </>
  )
}
